project_id = "wjxlzcuqpoamrwumszau"

[functions.sync-notion-reps]
verify_jwt = false

[functions.get-blitz-weather]
verify_jwt = false

[functions.generate-insights-feedback]
verify_jwt = false

[functions.generate-daily-focus]
verify_jwt = false
